version: "3.8"

services:
  minecraft:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      DEBUG: "TRUE"
      ONLINE_MODE: "FALSE"
      SERVER_NAME: "sleepydog"
      DIFFICULTY: "normal"
      VERSION: 1.18.2
      ICON: "https://freepngimg.com/thumb/cat/2-black-cat-png-image.png"
      OVERRIDE_ICON: "TRUE"
      VIEW_DISTANCE: 16
      ENABLE_ROLLING_LOGS: "TRUE"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - /home/l1tsolaiki/data:/data
