version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      DEBUG: "TRUE"
      ONLINE_MODE: "FALSE"
      SERVER_NAME: "sleepydog"
      DIFFICULTY: "normal"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - /home/l1tsolaiki/data:/data
